// let num = prompt("guess the number ")
// alert("give the number our friend as you assume")
// alert( "I give you number 50")
// alert("added both ")
// alert("give half charity ")
// alert(" and return our friend ")
// alert(" you have Reminder 25 ") 

alert("JavaScript Alert \n\nError! Please enter a valid password.")
alert("JavaScript Alert\n\nWelcome to JS Land...\nHappy Coding!")
alert("JavaScript Alert\n\nWelcome to JS Land...")
alert("JavaScript Alert\n\nHappy Coding!\nPrevent this page from creating additional dialogs.")
alert("JavaScript Alert\n\nHello... I can run JS through my web browser's console")
alert("JavaScript Alert\n\nGoodbye...")